version: "3.7"

networks:
  my_network:
    external: false

volumes:
  db-data:

services:
  &db-service prisma-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      my_network:
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
  &node-service prisma-node:
    ports:
      - 127.0.0.1:3000:3000
    image: node:18.12.0
    working_dir: "/home/node/app"
    depends_on:
      - *db-service
    volumes:
      - "./:/home/node/app/:rw"
    networks:
      my_network:
